### ISSUE TITLE
support for hiding certain tracks for specific playlist orders

### ISSUE THREAD

**Issue by vinegar97** [Deinonychus71/Sm5shMusic#14]
adding a music track to a stage playlist, and setting its order to "-1"  in any stage order hides it from the stage that uses said order and keeps it in other stages that share that playlist.

this even works through editing playlist_override.json directly in a text editor from what i tested, but I haven't seen any way to do it through the GUI.

**Comment by Deinonychus71** [comment]
Interesting, I wasn't aware!
Definitely a nice option to add!
