### ISSUE TITLE
"Edit a Mod" still says "Pick a Game to Edit"

### ISSUE THREAD

**Issue by Segtendo** [Deinonychus71/Sm5shMusic#15]
![Sm5shMusic GUI_2020-12-30_14-10-50](https://user-images.githubusercontent.com/76792055/103378729-ec0a6f00-4aa8-11eb-9386-2fb89fedd512.png)

Just a minor issue, but as the image shows, when editing a mod, the program thinks it's a game.

**Comment by Deinonychus71** [comment]
Fixed for next version
