### ISSUE TITLE
Songs stop playing after 30 seconds

### ISSUE THREAD

**Issue by Bur0ri** [Deinonychus71/Sm5shMusic#17]
The songs just go quiet after 30 seconds, is there a way I can fix that or should I wait for a patch?

**Comment by Demonslayerx8** [comment]
Is that in sound test, stage select when picking a song, or in a match?

Cause it's perfectly fine.

**Comment by Bur0ri** [comment]
All three, it even crashes in matches sometimes

**Comment by Demonslayerx8** [comment]
Are you following the guide that's up on Gamebanana properly?

**Comment by Bur0ri** [comment]
Yeah

**Comment by Bur0ri** [comment]
Maybe it has something to do with the language of my game...? I'll try setting it to English real quick

**Comment by Bur0ri** [comment]
I fixed it, I think it's because I transfered the files using FileZilla before

**Comment by Demonslayerx8** [comment]
I use FileZilla myself, and I've never had a issue with it. If you do have issues still with it, I suggest setting the connection transfer to 1 per file instead of multiple.

**Comment by Segtendo** [comment]
I'd personally copy them directly via SD card. I've had issues in the past with transferring large files over FTP, but that's just my preference.
