### ISSUE TITLE
Clicking the preview button too fast crashes

### ISSUE THREAD

**Issue by Segtendo** [Deinonychus71/Sm5shMusic#18]
As the title says, if one were to preview a song and click too fast to play and stop, the program locks up and closes down.

Example below.

https://user-images.githubusercontent.com/76792055/103422522-934ddb80-4b67-11eb-80eb-623bc469a78c.mp4

**Comment by Deinonychus71** [comment]
Yeah I'm aware but it's been low priority as you really got to want it to crash. Still good to report though!

**Comment by Deinonychus71** [comment]
fixed for next release
