### ISSUE TITLE
Enhancement: Copy Author/Copyright Info From Existing Songs

### ISSUE THREAD

**Issue by tawawy** [Deinonychus71/Sm5shMusic#24]
Title. Basically just the ability to dupe the author/copyright fields from songs already present in Ultimate.

For example, if I was to add another song from Sonic Lost World (like the final showdown or Honeycomb themes), I could copy the composers and SEGA copyright from Ultimate's existing implementation of the Windy Hill Zone theme. Hope this makes sense!

**Comment by Deinonychus71** [comment]
Would an option such as "Copy From..." and then list the last X most recent values help? I don't really want to add a full lookup in this control but I figured this could fit the bill quite nicely?

**Comment by Deinonychus71** [comment]
@tawawy Can you let me know whether the solution above would work for your scenario?
