### ISSUE TITLE
Pinch Music Not Working

### ISSUE THREAD

**Issue by Jimmy1839** [Deinonychus71/Sm5shMusic#27]
Modded pinch music does not work when combined with another modded song. I have tested this with several different songs on several different mod packs.

If you try to link two modded songs together as a base song and a pinch song, the pinch music will not play and instead will be completely silent.

However, you could add a modded song in, and set it as a pinch song for a base game song, and it will work fine. Vice versa, as well.

**Comment by Deinonychus71** [comment]
That is probably not the problem, several people have it working, including myself.

Can you ping me on discord to try and figure this one out?

**Comment by Deinonychus71** [comment]
Opened issue #28 as a result of this. Thanks!
