### ISSUE TITLE
In-game music added now has filler text and will crash

### ISSUE THREAD

**Issue by MillenniumSSB** [Deinonychus71/Sm5shMusic#29]
I'm not sure if this a known bug or if there is any solution to fixing it but I'm not sure where to ask so I figured this being a good place. 

I have been using Sm5sh Music for a while and I have had no issues with the software and the music in-game but I recently added some new music and now most of the custom music that has been added now has a filler text of sort and will crash when viewed in the sound test / my music, I have recorded this bug in action to show this glitch in action.

https://youtu.be/PGKkUZjV_s8

**Comment by Deinonychus71** [comment]
What version of the tool do you use, what version of the game? (what version number shows up next to the title in the tool?)
Did you modify the resource files? Have you tried to disable all other mods first?

I am not aware of this issue and this is the first time I see it. If you tried all the above send me your metadata.json file (or zip mod) on discord and I'll take a look

**Comment by MillenniumSSB** [comment]
Sm5sh Music is on Version 1 while the version of the game is 10.0. The files I have been using are from a music pack found on GameBanana and can be found here: https://gamebanana.com/gamefiles/14013

I have disabled all my other mods to see if that was an issue and even without mods the issue still shows up.

If you want to look at some of my files I would be happy to do so, My username is 𝐌𝐢𝐥𝐥𝐞𝐧𝐧𝐢𝐮𝐦#2000

**Comment by Deinonychus71** [comment]
And so this is the -only- mod that you compiled, correct?
why 10.0 and not 10.1 if I may ask?

**Comment by MillenniumSSB** [comment]
Good point, I just updated my files to the 10.1 versions and the issue is still there :/

**Comment by Deinonychus71** [comment]
Closing as the issue seems to be related to Arcropolis. Feel free to reopen if it happens again.
Thanks!
